---
- hosts: all
  #connection: local

  vars_files:
    - config.yml

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/killin10-setup.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/kube.yml
    - include_tasks: tasks/maven.yml
    - include_tasks: tasks/brew-apps.yml
    - include_tasks: tasks/vim.yml
    - include_tasks: tasks/rust.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/brew-cask-apps.yml
